/**
 * Created by alanmars on 15/4/22.
 */
var ProtocolType = {
    Common: {
        C2S_LOGIN: "c2s_login",

        S2C_LOGIN: "s2c_login"
    },
    Slot: {
        C2S_GET_SUBJECTS: "c2s_get_subjects",
        C2S_SPIN: "c2s_spin",
        C2S_ENTER_ROOM: "c2s_enter_room",
        C2S_UPDATE_PRIZE_POOL_PLAYERS: "c2s_update_prize_pool_players",
        C2S_GET_SUBJECT_JACKPOT_INFOS: "c2s_get_subject_jackpot_infos",
        C2S_GET_JACKPOT_RECORDS: "c2s_get_jackpot_records",
        C2S_UNLOCK_SUBJECT: "c2s_unlock_subject",
        C2S_SLOT_PARAM: "c2s_slot_param",

        S2C_GET_SUBJECTS: "s2c_get_subjects",
        S2C_SPIN: "s2c_spin",
        S2C_ENTER_ROOM: "s2c_enter_room",
        S2C_UPDATE_PRIZE_POOL_PLAYERS: "s2c_update_prize_pool_players",
        S2C_PRIZE_POOL_RESULT: "s2c_prize_pool_result",
        S2C_OTHER_WIN_JACKPOT: "s2c_other_win_jackpot",
        S2C_GET_SUBJECT_JACKPOT_INFOS: "s2c_get_subject_jackpot_infos",
        S2C_GET_JACKPOT_RECORDS: "s2c_get_jackpot_records",
        S2C_UNLOCK_SUBJECT: "s2c_unlock_subject",
        S2C_SLOT_PARAM: "s2c_slot_param"
    },
    Social: {
        C2S_GET_HOURLY_BONUS: "c2s_get_hourly_bonus",
        C2S_CLAIM_HOURLY_BONUS: "c2s_claim_hourly_bonus",
        C2S_GET_DAILY_BONUS: "c2s_get_daily_bonus",
        C2S_CLAIM_DAILY_BONUS: "c2s_claim_daily_bonus",
        C2S_VERIFY_PURCHASE: "c2s_verify_purchase",
        C2S_GET_REWARD: "c2s_get_reward",
        C2S_CLAIM_REWARD: "c2s_claim_reward",
        C2S_GET_SHOPS: "c2s_get_shops",
        C2S_AD_CONTROL: "c2s_ad_control",
        C2S_GET_PROCESSING_PURCHASE: "c2s_get_processing_purchase",
        C2S_INVITE_FB_FRIENDS: "c2s_invite_fb_friends",
        C2S_GET_SYSTEM_MESSAGE: "c2s_get_system_message",
        C2S_GET_MULTI_HOURLY_BONUS: "c2s_get_multi_hourly_bonus",
        C2S_CLAIM_MULTI_HOURLY_BONUS: "c2s_claim_multi_hourly_bonus",
        C2S_CLAIM_KEY_REWARD: "c2s_claim_key_reward",
        C2S_FB_NOTI_CLICK: "c2s_fb_noti_click",
        C2S_GET_MAILS: "c2s_get_mails",
        C2S_READ_MAILS: "c2s_read_mails",
        C2S_SEND_MAIL: "c2s_send_mail",
        C2S_LIKE_US: "c2s_like_us",
        C2S_CONSUME_PURCHASE: "c2s_consume_purchase",
        C2S_CLAIM_VIP_DAILY_REWARD: "c2s_claim_vip_daily_reward",
        C2S_GET_HOURLY_GAME: "c2s_get_hourly_game",
        C2S_UPGRADE_HOURLY_GAME_CARD: "c2s_upgrade_hourly_game_card",
        C2S_GEN_HOURLY_GAME: "c2s_gen_hourly_game",
        C2S_CLAIM_HOURLY_GAME: "c2s_claim_hourly_game",
        C2S_UNLOCK_HOURLY_GAME: "c2s_unlock_hourly_game",
        C2S_CLAIM_VIDEO_AD_REWARD:"c2s_claim_video_ad_reward",
        C2S_UPDATE_INCENTIVE_AD:"c2s_update_incentive_ad",
        C2S_GET_INCENTIVE_AD:"c2s_get_incentive_ad",
        C2S_DAILY_SHOP_POP_UP:"c2s_daily_shop_pop_up",

        S2C_REWARD_NOTICE: "s2c_reward_notice",
        S2C_GET_HOURLY_BONUS: "s2c_get_hourly_bonus",
        S2C_CLAIM_HOURLY_BONUS: "s2c_claim_hourly_bonus",
        S2C_GET_DAILY_BONUS: "s2c_get_daily_bonus",
        S2C_CLAIM_DAILY_BONUS: "s2c_claim_daily_bonus",
        S2C_VERIFY_PURCHASE: "s2c_verify_purchase",
        S2C_CLAIM_REWARD: "s2c_claim_reward",
        S2C_GET_SHOPS: "s2c_get_shops",
        S2C_AD_CONTROL: "s2c_ad_control",
        S2C_FB_IAP_NOTICE: "s2c_fb_iap_notice",
        S2C_INVITE_FB_FRIENDS: "s2c_invite_fb_friends",
        S2C_SYSTEM_MESSAGE_NOTICE: "s2c_system_message_notice",
        S2C_GET_MULTI_HOURLY_BONUS: "s2c_get_multi_hourly_bonus",
        S2C_CLAIM_MULTI_HOURLY_BONUS: "s2c_claim_multi_hourly_bonus",
        S2C_CLAIM_KEY_REWARD: "s2c_claim_key_rewward",
        S2C_FB_NOTI_CLICK: "s2c_fb_noti_click",
        S2C_GET_MAILS: "s2c_get_mails",
        S2C_READ_MAILS: "s2c_read_mails",
        S2C_SEND_MAIL: "s2c_send_mail",
        S2C_LIKE_US: "s2c_like_us",
        S2C_CONSUME_PURCHASE: "s2c_consume_purchase",
        S2C_CLAIM_VIP_DAILY_REWARD: "s2c_claim_vip_daily_reward",
        S2C_GET_HOURLY_GAME: "s2c_get_hourly_game",
        S2C_UPGRADE_HOURLY_GAME_CARD: "s2c_upgrade_hourly_game_card",
        S2C_GEN_HOURLY_GAME: "s2c_gen_hourly_game",
        S2C_CLAIM_HOURLY_GAME: "s2c_claim_hourly_game",
        S2C_UNLOCK_HOURLY_GAME: "s2c_unlock_hourly_game",
        S2C_INCENTIVE_AD :"s2c_incentive_ad",
        S2C_INCENTIVE_STATE_UPDATE :"s2c_incentive_state_update",
        S2C_DAILY_SHOP_POP_UP:"s2c_daily_shop_pop_up",
        S2C_CLAIM_VIDEO_AD_REWARD:"s2c_claim_video_ad_reward"
    },
    Task: {
        C2S_GET_CUR_TASK: "c2s_get_cur_task",
        C2S_COMPLETE_TASK: "c2s_complete_task",
        C2S_GET_DAILY_TASK: "c2s_get_daily_task",
        C2S_CLAIM_DAILY_TASK_REWARD: "c2s_claim_daily_task_reward",
        C2S_GET_FRIEND_TASK: "c2s_get_friend_task",

        S2C_GET_CUR_TASK: "s2c_get_cur_task",
        S2C_COMPLETE_TASK: "s2c_complete_task",
        S2C_GET_DAILY_TASK: "s2c_get_daily_task",
        S2C_SYNC_DAILY_TASK: "s2c_sync_daily_task",
        S2C_CLAIM_DAILY_TASK_REWARD: "s2c_claim_daily_task_reward",
        S2C_GET_FRIEND_TASK: "s2c_get_friend_task"
    }
};

module.exports = ProtocolType;