/**
 * Created by alanmars on 15/4/18.
 */
var SlotNoticeType = {
    SLOT_NOTICE_SPIN_RESULT_RECEIVED: 0,
    SLOT_NOTICE_SPIN_RESULT_START: 1,
    SLOT_NOTICE_FIVE_OF_KIND: 2,
    SLOT_NOTICE_BIG_WIN: 3,
    SLOT_NOTICE_MEGA_WIN: 4,
    SLOT_NOTICE_BONUS: 5,
    SLOT_NOTICE_SPECIAL_ANIMATION: 6,
    SLOT_NOTICE_SUBJECT_NOTIFY: 7,

    SLOT_NOTICE_COLOSSAL_WIN: 8,
    SLOT_NOTICE_JACKPOT: 9,

    SLOT_NOTICE_LEVEL_UP: 10,

    SLOT_NOTICE_SHOW_CONNECTED_AREA: 11
};

module.exports = SlotNoticeType;