/**
 * Created by alanmars on 15/4/18.
 */
var SlotSpinStepEndType = {
    SLOT_STEP_SPIN_END: 0,
    SLOT_STEP_BLINK_JACKPOT_END: 1,
    SLOT_STEP_BLINK_ALL_WIN_LINE_END: 2,
    SLOT_STEP_BLINK_WIN_LINE_ROUND_END: 3,
    SLOT_STEP_BLINK_BONUS_LINE_END: 4,
    SLOT_STEP_BLINK_SCATTER_END: 5,
    SLOT_STEP_BONUS_WELCOME_END: 6,
    SLOT_STEP_BONUS_RESULT_END: 7,
    SLOT_STEP_FREE_SPIN_WELCOME_END: 8,
    SLOT_STEP_FREE_SPIN_RESULT_END: 9,
    SLOT_STEP_SPECIAL_ANIMATION_END: 10,
    SLOT_STEP_DROP_EXPLOSION_END: 11,
    SLOT_STEP_SHOW_CONNECTED_AREA_END: 12,
    SLOT_STEP_SHOW_SPECIAL_TASK_ANIMATION_END: 13
};

module.exports = SlotSpinStepEndType;