/**
 * Created by alanmars on 15/4/20.
 */

var SlotUIType = {
    SLOT_SPIN_ITEM_TRIGGERED: 0,
    SLOT_CHAT_ITEM_TRIGGERED: 1,
    SLOT_STOP_ITEM_TRIGGERED: 2,
    SLOT_ADD_BET_ITEM_TRIGGERED: 3,
    SLOT_MINUS_BET_ITEM_TRIGGERED: 4,
    SLOT_MAX_BET_ITEM_TRIGGERED: 5,
    SLOT_MAP_ITEM_TRIGGERED: 6,
    SLOT_CHANGE_BET_GRADE_ITEM_TRIGGERED: 7,
    SLOT_AUTO_SPIN_ITEM_TRIGGERED: 8,
    SLOT_CHANGE_BET_ITEM_TRIGGERED : 9,
    SLOT_ADD_LINE_NUM_ITEM_TRIGGERED: 10,
    SLOT_MINUS_LINE_NUM_ITEM_TRIGGERED: 11,
    SLOT_AUTO_SPIN_STOP_ITEM_TRIGGERED: 12,
    SLOT_FREE_SPIN_ITEM_TRIGGERED: 13
};

module.exports = SlotUIType;